// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AchieveGoal(arg1) {
  return window['go']['main']['App']['AchieveGoal'](arg1);
}

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AddReward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddReward'](arg1, arg2, arg3, arg4, arg5);
}

export function AutoPauseInactiveActivities(arg1, arg2) {
  return window['go']['main']['App']['AutoPauseInactiveActivities'](arg1, arg2);
}

export function CompleteSchedule(arg1) {
  return window['go']['main']['App']['CompleteSchedule'](arg1);
}

export function CreateActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateActivity'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateChild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateChild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateFlashcard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFlashcard'](arg1, arg2, arg3, arg4);
}

export function CreateGoal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateGoal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNoteTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNoteTemplate'](arg1, arg2, arg3);
}

export function CreateRecurringSchedules(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateRecurringSchedules'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateSchedule(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateSchedule'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DeleteActivity(arg1) {
  return window['go']['main']['App']['DeleteActivity'](arg1);
}

export function DeleteChild(arg1) {
  return window['go']['main']['App']['DeleteChild'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNoteTemplate(arg1) {
  return window['go']['main']['App']['DeleteNoteTemplate'](arg1);
}

export function DeleteReward(arg1) {
  return window['go']['main']['App']['DeleteReward'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function EndActivityInSession(arg1, arg2) {
  return window['go']['main']['App']['EndActivityInSession'](arg1, arg2);
}

export function EndSession(arg1, arg2) {
  return window['go']['main']['App']['EndSession'](arg1, arg2);
}

export function ExportCSVFile(arg1, arg2) {
  return window['go']['main']['App']['ExportCSVFile'](arg1, arg2);
}

export function ExportPDFFile(arg1, arg2) {
  return window['go']['main']['App']['ExportPDFFile'](arg1, arg2);
}

export function GenerateSessionSummary(arg1) {
  return window['go']['main']['App']['GenerateSessionSummary'](arg1);
}

export function GetActiveActivitiesInSession(arg1) {
  return window['go']['main']['App']['GetActiveActivitiesInSession'](arg1);
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetActivityByID(arg1) {
  return window['go']['main']['App']['GetActivityByID'](arg1);
}

export function GetActivityTrends(arg1, arg2) {
  return window['go']['main']['App']['GetActivityTrends'](arg1, arg2);
}

export function GetAllActivities() {
  return window['go']['main']['App']['GetAllActivities']();
}

export function GetAllChildren() {
  return window['go']['main']['App']['GetAllChildren']();
}

export function GetAllNoteTemplates() {
  return window['go']['main']['App']['GetAllNoteTemplates']();
}

export function GetChildActivityFrequency(arg1) {
  return window['go']['main']['App']['GetChildActivityFrequency'](arg1);
}

export function GetChildByID(arg1) {
  return window['go']['main']['App']['GetChildByID'](arg1);
}

export function GetChildComparisonStats() {
  return window['go']['main']['App']['GetChildComparisonStats']();
}

export function GetChildGoals(arg1) {
  return window['go']['main']['App']['GetChildGoals'](arg1);
}

export function GetChildNoteKeywordFrequency(arg1) {
  return window['go']['main']['App']['GetChildNoteKeywordFrequency'](arg1);
}

export function GetChildProgressSummary(arg1) {
  return window['go']['main']['App']['GetChildProgressSummary'](arg1);
}

export function GetChildRewardTrends(arg1) {
  return window['go']['main']['App']['GetChildRewardTrends'](arg1);
}

export function GetChildRewards(arg1) {
  return window['go']['main']['App']['GetChildRewards'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetFlashcardsByCategory(arg1) {
  return window['go']['main']['App']['GetFlashcardsByCategory'](arg1);
}

export function GetMonthlyReportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMonthlyReportData'](arg1, arg2, arg3);
}

export function GetMostPopularActivity() {
  return window['go']['main']['App']['GetMostPopularActivity']();
}

export function GetProgressMetrics(arg1) {
  return window['go']['main']['App']['GetProgressMetrics'](arg1);
}

export function GetRewardSummary(arg1) {
  return window['go']['main']['App']['GetRewardSummary'](arg1);
}

export function GetScheduleByID(arg1) {
  return window['go']['main']['App']['GetScheduleByID'](arg1);
}

export function GetScheduleStats(arg1) {
  return window['go']['main']['App']['GetScheduleStats'](arg1);
}

export function GetSchedulesByChild(arg1) {
  return window['go']['main']['App']['GetSchedulesByChild'](arg1);
}

export function GetSessionActivities(arg1) {
  return window['go']['main']['App']['GetSessionActivities'](arg1);
}

export function GetSessionActivityHistoryByChild(arg1) {
  return window['go']['main']['App']['GetSessionActivityHistoryByChild'](arg1);
}

export function GetSessionByID(arg1) {
  return window['go']['main']['App']['GetSessionByID'](arg1);
}

export function GetSessionNotes(arg1) {
  return window['go']['main']['App']['GetSessionNotes'](arg1);
}

export function GetSessionProgress(arg1) {
  return window['go']['main']['App']['GetSessionProgress'](arg1);
}

export function GetSessionStatistics(arg1, arg2) {
  return window['go']['main']['App']['GetSessionStatistics'](arg1, arg2);
}

export function GetSessionsByChild(arg1) {
  return window['go']['main']['App']['GetSessionsByChild'](arg1);
}

export function GetTodaySchedules(arg1) {
  return window['go']['main']['App']['GetTodaySchedules'](arg1);
}

export function GetTodaySessionsCount() {
  return window['go']['main']['App']['GetTodaySessionsCount']();
}

export function GetUpcomingSchedules(arg1, arg2) {
  return window['go']['main']['App']['GetUpcomingSchedules'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogFlashcardResponse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFlashcardResponse'](arg1, arg2, arg3, arg4);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ShowErrorNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorNotification'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartActivityInSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartActivityInSession'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function UpdateActivity(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateActivity'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateActivityInSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateActivityInSession'](arg1, arg2);
}

export function UpdateChild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateChild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateNoteTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNoteTemplate'](arg1, arg2, arg3, arg4);
}

export function UpdateSchedule(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateSchedule'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateSessionSummaryNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionSummaryNotes'](arg1, arg2);
}

export function ValidateSession(arg1) {
  return window['go']['main']['App']['ValidateSession'](arg1);
}
